# TASK #1: DEFINE SINGLE AND MULTI-DIMENSIONAL  NUMPY ARRAYS

In [3]:
# NumPy is a Linear Algebra Library used for multidimensional arrays
# NumPy brings the best of two worlds: (1) C/Fortran computational efficiency, (2) Python language easy syntax 

import numpy as np

# Let's define a one-dimensional array 

my_list =[50,60,80,100,200,300,500,600]
my_list

[50, 60, 80, 100, 200, 300, 500, 600]

In [6]:
type(my_list)

list

In [4]:
# Let's create a numpy array from the list "my_list"
my_numpy_array=np.array(my_list)
my_numpy_array

array([ 50,  60,  80, 100, 200, 300, 500, 600])

In [5]:
type(my_numpy_array)

numpy.ndarray

In [11]:
# Multi-dimensional (Matrix definition) 
my_matrix=np.array([[2,5,8],[7,3,6]])
my_matrix

array([[2, 5, 8],
       [7, 3, 6]])

In [12]:
type(my_matrix)

numpy.ndarray

MINI CHALLENGE #1: 
- Write a code that creates the following 2x4 numpy array

```
[[3 7 9 3] 
[4 3 2 2]]
```

In [14]:
my_matrix2=np.array([[3, 7, 9 ,3] ,[4 ,3 ,2 ,2]])
my_matrix2

array([[3, 7, 9, 3],
       [4, 3, 2, 2]])

In [15]:
type(my_matrix2)

numpy.ndarray

# TASK #2: LEVERAGE NUMPY BUILT-IN METHODS AND FUNCTIONS 

In [41]:
# "rand()" uniform distribution between 0 and 1
x=np.random.rand(20)
x

array([0.95541284, 0.03515544, 0.28800163, 0.96913366, 0.43722482,
       0.08766916, 0.71611039, 0.12273838, 0.66477422, 0.45800223,
       0.29690081, 0.84875264, 0.5958335 , 0.44498979, 0.61412413,
       0.98480681, 0.0048823 , 0.399462  , 0.92516116, 0.06110405])

In [17]:
# you can create a matrix of random number as well
x=np.random.rand(7,2)
x

array([[0.94931338, 0.01506877],
       [0.11412561, 0.5217383 ],
       [0.20281509, 0.97693623],
       [0.99693731, 0.85311227],
       [0.14378785, 0.22666117],
       [0.52122855, 0.42358826],
       [0.87771121, 0.65379411]])

In [23]:
# "randint" is used to generate random integers between upper and lower bounds
x=np.random.randint(10000)
x

5609

In [42]:
# "randint" can be used to generate a certain number of random itegers as follows
x=np.random.randint(2,70,5)
x

array([10,  8,  6, 17, 17])

In [28]:
# np.arange creates an evenly spaced values within a given interval
x=np.arange(1,10)
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
x=np.arange(1,10,2)
x

array([1, 3, 5, 7, 9])

In [33]:
# create a diagonal of ones and zeros everywhere else
x=np.eye(3)
x

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [38]:
# Matrix of ones
x=np.ones((5,5))
x

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [40]:
# Array of zeros
x=np.zeros((5,5))
x

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

MINI CHALLENGE #2:
- Write a code that takes in a positive integer "x" from the user and creates a 1x10 array with random numbers ranging from 0 to "x"

In [50]:
#Option 1: We defined a function
def my_array(x):
    y=np.random.randint(1,x,10)
    return y

In [51]:
my_array(20)

array([ 5,  6, 11,  7, 10, 11, 17, 15, 17,  8])

In [61]:
#Option 2: Using input
x=int(input('Enter a number :'))
y=np.random.randint(1,x,10)
y

Enter a number :50


array([36, 16, 24,  2, 40, 39, 15, 43, 30, 23])

# TASK #3: PERFORM MATHEMATICAL OPERATIONS IN NUMPY

In [62]:
# np.arange() returns an evenly spaced values within a given interval
x=np.arange(1,10)
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [71]:
y=np.arange(1,10)
y

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [72]:
# Add 2 numpy arrays together
sum=x+y
sum

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [73]:
square=x**2
square

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])

In [74]:
sqrt = np.sqrt(square)
sqrt

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [75]:
z=np.exp(y)
z

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03])

MINI CHALLENGE #3:
- Given the X and Y values below, obtain the distance between them

```
X = [5, 7, 20]
Y = [9, 15, 4]
```

In [76]:
x=np.array([5,7,20])
y=np.array([9,15,4])

In [78]:
z=np.sqrt(x**2 + y**2)
z

array([10.29563014, 16.55294536, 20.39607805])

# TASK #4: PERFORM ARRAYS SLICING AND INDEXING 

In [80]:
my_numpy_array= np.array([3,5,6,2,8,10,20,50])
my_numpy_array

array([ 3,  5,  6,  2,  8, 10, 20, 50])

In [81]:
# Access specific index from the numpy array
my_numpy_array[1]

5

In [82]:
# Starting from the first index 0 up until and NOT including the last element
my_numpy_array[:-1]

array([ 3,  5,  6,  2,  8, 10, 20])

In [83]:
# Broadcasting, altering several values in a numpy array at once
my_numpy_array[0:4]=7
my_numpy_array

array([ 7,  7,  7,  7,  8, 10, 20, 50])

In [97]:
# Let's define a two dimensional numpy array
matrix=np.random.randint(1,10,(6,6))
matrix

array([[5, 8, 9, 4, 6, 7],
       [5, 4, 7, 7, 2, 4],
       [3, 3, 1, 5, 7, 5],
       [6, 8, 3, 1, 5, 7],
       [3, 4, 2, 8, 5, 3],
       [5, 3, 9, 7, 7, 1]])

In [98]:
# Get a row from a matrix
matrix[4]

array([3, 4, 2, 8, 5, 3])

In [99]:
# Get one element
matrix[4][2]

2

MINI CHALLENGE #4:
- In the following matrix, replace the last row with 0

```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```



In [103]:
x=np.array([[2, 30, 20, -2, -4],
    [3, 4 , 40, -3 ,-2],
    [-3, 4, -6 ,90, 10],
    [25, 45, 34, 22, 12],
    [13 ,24 ,22, 32 ,37]])

In [104]:
x[4]=0
x

array([[ 2, 30, 20, -2, -4],
       [ 3,  4, 40, -3, -2],
       [-3,  4, -6, 90, 10],
       [25, 45, 34, 22, 12],
       [ 0,  0,  0,  0,  0]])

# TASK #5: PERFORM ELEMENTS SELECTION (CONDITIONAL)

In [105]:
matrix= np.random.randint(1,10,(5,5))
matrix

array([[8, 8, 2, 9, 4],
       [6, 2, 9, 7, 2],
       [2, 6, 5, 7, 2],
       [7, 4, 3, 2, 6],
       [5, 1, 5, 2, 4]])

In [108]:
new_matrix=matrix>7
new_matrix

array([[ True,  True, False,  True, False],
       [False, False,  True, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [109]:
new_matrix2=matrix[matrix>7]
new_matrix2

array([8, 8, 9, 9])

In [110]:
# Obtain odd elements only
new_matrix3= matrix[matrix%2!=0]
new_matrix3

array([9, 9, 7, 5, 7, 7, 3, 5, 1, 5])

In [113]:
# Obtain odd elements only
#another option
new_matrix4= matrix[matrix%2==1]
new_matrix4

array([9, 9, 7, 5, 7, 7, 3, 5, 1, 5])

MINI CHALLENGE #5:
- In the following matrix, replace negative elements by 0 and replace odd elements with -2


```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```


In [128]:
x=np.array([[2, 30 ,20, -2, -4],
    [3, 4 , 40, -3, -2],
    [-3, 4 ,-6 ,90, 10],
    [25, 45, 34 ,22 ,12],
    [13, 24 ,22 ,32 ,37]])

In [129]:
x

array([[ 2, 30, 20, -2, -4],
       [ 3,  4, 40, -3, -2],
       [-3,  4, -6, 90, 10],
       [25, 45, 34, 22, 12],
       [13, 24, 22, 32, 37]])

In [134]:
x[x<0]=0
x[x%2!=0]=-2
x

array([[ 2, 30, 20,  0,  0],
       [-2,  4, 40,  0,  0],
       [ 0,  4,  0, 90, 10],
       [-2, -2, 34, 22, 12],
       [-2, 24, 22, 32, -2]])

# TASK #6: UNDERSTAND PANDAS FUNDAMENTALS

In [ ]:
# Pandas is a data manipulation and analysis tool that is built on Numpy.
# Pandas uses a data structure known as DataFrame (think of it as Microsoft excel in Python). 
# DataFrames empower programmers to store and manipulate data in a tabular fashion (rows and columns).
# Series Vs. DataFrame? Series is considered a single column of a DataFrame.

In [135]:
import pandas as pd

In [138]:
# Let's define a two-dimensional Pandas DataFrame
# Note that you can create a pandas dataframe from a python dictionary
bank_client_df= pd.DataFrame({'Bank Client ID':[111, 222, 333, 444],
                             'Bank Client Name':['Purva','Swaraj','Kirti','Aniruddha'],
                             'Net Worth[£]':[3500, 29000, 10000, 2000],
                             'Years with Bank':[3,4,9,5]})
bank_client_df

Bank Client ID Bank Client Name  Net Worth[£]  Years with Bank
0             111            Purva          3500                3
1             222           Swaraj         29000                4
2             333            Kirti         10000                9
3             444        Aniruddha          2000                5

In [140]:
# Let's obtain the data type 
type(bank_client_df)

pandas.core.frame.DataFrame

In [142]:
# you can only view the first couple of rows using .head()
bank_client_df.head(2)

Bank Client ID Bank Client Name  Net Worth[£]  Years with Bank
0             111            Purva          3500                3
1             222           Swaraj         29000                4

In [143]:
# you can only view the last couple of rows using .tail()
bank_client_df.tail(2)

Bank Client ID Bank Client Name  Net Worth[£]  Years with Bank
2             333            Kirti         10000                9
3             444        Aniruddha          2000                5

MINI CHALLENGE #6:
- A porfolio contains a collection of securities such as stocks, bonds and ETFs. Define a dataframe named 'portfolio_df' that holds 3 different stock ticker symbols, number of shares, and price per share (feel free to choose any stocks)
- Calculate the total value of the porfolio including all stocks

In [145]:
portfolio_df=pd.DataFrame({'stock_ticker_symbols':['AAPL','GOOGL','META'],
                          'number_of_shares':[10, 4, 2],
                          'price_per_share[$]':[158.91,108.94,157.16]})
portfolio_df

stock_ticker_symbols  number_of_shares  price_per_share[$]
0                 AAPL                10              158.91
1                GOOGL                 4              108.94
2                 META                 2              157.16

In [159]:
total_value=(portfolio_df['number_of_shares']*portfolio_df['price_per_share[$]']).sum()
print(f'The total value is  : ${total_value}')

The total value is  : $2339.18


# TASK #7: PANDAS WITH CSV AND HTML DATA

In [160]:
# Read tabular data using read_html
house_price_df=pd.read_html('https://www.livingin-canada.com/house-prices-canada.html')

In [162]:
house_price_df[0]

City  \
0                                      Vancouver, BC   
1                                       Toronto, Ont   
2                                        Ottawa, Ont   
3                                       Calgary, Alb   
4                                      Montreal, Que   
5                                        Halifax, NS   
6                                       Regina, Sask   
7                                    Fredericton, NB   
8  (adsbygoogle = window.adsbygoogle || []).push(...   

                                 Average House Price  \
0                                         $1,036,000   
1                                           $870,000   
2                                           $479,000   
3                                           $410,000   
4                                           $435,000   
5                                           $331,000   
6                                           $254,000   
7                                           $198,000   
8  (adsbygoogle = window.adsbygoogle || []).push(...   

                                     12 Month Change  
0                                           + 2.63 %  
1                                            +10.2 %  
2                                           + 15.4 %  
3                                            – 1.5 %  
4                                            + 9.3 %  
5                                            + 3.6 %  
6                                            – 3.9 %  
7                                            – 4.3 %  
8  (adsbygoogle = window.adsbygoogle || []).push(...

In [164]:
house_price_df[-1]

Province  \
0                                    British Columbia   
1                                             Ontario   
2                                             Alberta   
3                                              Quebec   
4                                            Manitoba   
5                                        Saskatchewan   
6                                         Nova Scotia   
7                                Prince Edward Island   
8                             Newfoundland / Labrador   
9                                       New Brunswick   
10                                   Canadian Average   
11  (adsbygoogle = window.adsbygoogle || []).push(...   

                                  Average House Price  \
0                                            $736,000   
1                                            $594,000   
2                                            $353,000   
3                                            $340,000   
4                                            $295,000   
5                                            $271,000   
6                                            $266,000   
7                                            $243,000   
8                                            $236,000   
9                                            $183,000   
10                                           $488,000   
11  (adsbygoogle = window.adsbygoogle || []).push(...   

                                      12 Month Change  
0                                             + 7.6 %  
1                                             – 3.2 %  
2                                             – 7.5 %  
3                                             + 7.6 %  
4                                             – 1.4 %  
5                                             – 3.8 %  
6                                             + 3.5 %  
7                                             + 3.0 %  
8                                             – 1.6 %  
9                                             – 2.2 %  
10                                            – 1.3 %  
11  (adsbygoogle = window.adsbygoogle || []).push(...

In [170]:
# Pandas is used to read a csv file and store data in a DataFrame
sample_df=pd.read_csv(r'C:\Users\PurvaRaut\Desktop\DataAnalytics\4.SQL\SQL_Project\employees.csv')

In [172]:
sample_df.head()

EMP_ID FIRST_NAME LAST_NAME GENDER                      ROLE     DEPT  EXP  \
0   E260        Roy   Collins      M     SENIOR DATA SCIENTIST   RETAIL    7   
1   E245       Nian      Zhen      M     SENIOR DATA SCIENTIST   RETAIL    6   
2   E620    Katrina     Allen      F     JUNIOR DATA SCIENTIST   RETAIL    2   
3   E640    Jenifer    Jhones      F     JUNIOR DATA SCIENTIST   RETAIL    1   
4   E403      Steve   Hoffman      M  ASSOCIATE DATA SCIENTIST  FINANCE    4   

    COUNTRY      CONTINENT  SALARY  EMP_RATING MANAGER ID  
0     INDIA           ASIA    7000           3       E583  
1     CHINA           ASIA    6500           2       E583  
2     INDIA           ASIA    3000           1       E612  
3  COLOMBIA  SOUTH AMERICA    2800           4       E612  
4       USA  NORTH AMERICA    5000           3       E103

MINI CHALLENGE #7:
- Write a code that uses Pandas to read tabular US retirement data
- You can use data from here: https://www.ssa.gov/oact/progdata/nra.html 

In [165]:
US_retirement_df= pd.read_html('https://www.ssa.gov/oact/progdata/nra.html')

In [166]:
US_retirement_df[0]

Year of birth  \
0                                      1937 and prior   
1                                                1938   
2                                                1939   
3                                                1940   
4                                                1941   
5                                                1942   
6                                             1943-54   
7                                                1955   
8                                                1956   
9                                                1957   
10                                               1958   
11                                               1959   
12                                     1960 and later   
13  Notes: 1. Persons born on January 1 of any yea...   

                                                  Age  
0                                                  65  
1                                     65 and 2 months  
2                                     65 and 4 months  
3                                     65 and 6 months  
4                                     65 and 8 months  
5                                    65 and 10 months  
6                                                  66  
7                                     66 and 2 months  
8                                     66 and 4 months  
9                                     66 and 6 months  
10                                    66 and 8 months  
11                                   66 and 10 months  
12                                                 67  
13  Notes: 1. Persons born on January 1 of any yea...

# TASK #8: PANDAS OPERATIONS

In [173]:
# Let's define a dataframe as follows:
bank_client_df= pd.DataFrame({'Bank Client ID':[111, 222, 333, 444],
                             'Bank Client Name':['Purva','Swaraj','Kirti','Aniruddha'],
                             'Net Worth[£]':[3500, 29000, 10000, 2000],
                             'Years with Bank':[3,4,9,5]})
bank_client_df

Bank Client ID Bank Client Name  Net Worth[£]  Years with Bank
0             111            Purva          3500                3
1             222           Swaraj         29000                4
2             333            Kirti         10000                9
3             444        Aniruddha          2000                5

In [176]:
# Pick certain rows that satisfy a certain criteria 
df_loyal=bank_client_df[bank_client_df['Years with Bank']>=5]
df_loyal

Bank Client ID Bank Client Name  Net Worth[£]  Years with Bank
2             333            Kirti         10000                9
3             444        Aniruddha          2000                5

In [177]:
# Delete a column from a DataFrame
del bank_client_df['Bank Client ID']
bank_client_df

Bank Client Name  Net Worth[£]  Years with Bank
0            Purva          3500                3
1           Swaraj         29000                4
2            Kirti         10000                9
3        Aniruddha          2000                5

MINI CHALLENGE #8:
- Using "bank_client_df" DataFrame, leverage pandas operations to only select high networth individuals with minimum $5000 
- What is the combined networth for all customers with 5000+ networth?

In [178]:
high_networth_individuals_df=bank_client_df[bank_client_df['Net Worth[£]']>=5000]
high_networth_individuals_df

Bank Client Name  Net Worth[£]  Years with Bank
1           Swaraj         29000                4
2            Kirti         10000                9

In [187]:
total=high_networth_individuals_df['Net Worth[£]'].sum()

In [191]:
print(f'Combined networth for all customers with 5000+ networth is :£ {total}')

Combined networth for all customers with 5000+ networth is :£ 39000


# TASK #9: PANDAS WITH FUNCTIONS

In [ ]:
# Let's define a dataframe as follows:
bank_client_df = pd.DataFrame({'Bank client ID':[111, 222, 333, 444], 
                               'Bank Client Name':['Chanel', 'Steve', 'Mitch', 'Ryan'], 
                               'Net worth [$]':[3500, 29000, 10000, 2000], 
                               'Years with bank':[3, 4, 9, 5]})
bank_client_df

In [192]:
# Define a function that increases all clients networth (stocks) by a fixed value of 20% (for simplicity sake)
def networth_update(balance):
    return balance*1.2

In [193]:
# You can apply a function to the DataFrame 
bank_client_df['Net Worth[£]'].apply(networth_update)

0     4200.0
1    34800.0
2    12000.0
3     2400.0
Name: Net Worth[£], dtype: float64

In [195]:
bank_client_df['Bank Client Name'].apply(len)

0    5
1    6
2    5
3    9
Name: Bank Client Name, dtype: int64

MINI CHALLENGE #9:
- Define a function that triples the stock prices and adds $200
- Apply the function to the DataFrame
- Calculate the updated total networth of all clients combined

In [196]:
def increased_stock_price(stock_price):
    return (stock_price*3)+200    

In [199]:
new_bank_df= bank_client_df['Net Worth[£]'].apply(increased_stock_price)

In [200]:
new_bank_df

0    10700
1    87200
2    30200
3     6200
Name: Net Worth[£], dtype: int64

In [201]:
new_bank_df.sum()

134300

# TASK #10: PERFORM SORTING AND ORDERING IN PANDAS

In [202]:
# Let's define a dataframe as follows:
bank_client_df = pd.DataFrame({'Bank client ID':[111, 222, 333, 444], 
                               'Bank Client Name':['Chanel', 'Steve', 'Mitch', 'Ryan'], 
                               'Net worth [$]':[3500, 29000, 10000, 2000], 
                               'Years with bank':[3, 4, 9, 5]})
bank_client_df

Bank client ID Bank Client Name  Net worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4
2             333            Mitch          10000                9
3             444             Ryan           2000                5

In [203]:
# You can sort the values in the dataframe according to number of years with bank
bank_client_df.sort_values(by = 'Years with bank')

Bank client ID Bank Client Name  Net worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4
3             444             Ryan           2000                5
2             333            Mitch          10000                9

In [204]:
# Note that nothing changed in memory! you have to make sure that inplace is set to True
bank_client_df

Bank client ID Bank Client Name  Net worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4
2             333            Mitch          10000                9
3             444             Ryan           2000                5

In [205]:
# Set inplace = True to ensure that change has taken place in memory 
bank_client_df.sort_values(by='Years with bank',inplace=True)

In [206]:
# Note that now the change (ordering) took place 
bank_client_df

Bank client ID Bank Client Name  Net worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4
3             444             Ryan           2000                5
2             333            Mitch          10000                9

# TASK #11: PERFORM CONCATENATING AND MERGING WITH PANDAS

In [ ]:
# Check this out: https://pandas.pydata.org/pandas-docs/stable/user_guide/merging.html

In [211]:
df1=pd.DataFrame({'A':['A0','A1','A2','A3'],
                 'B':['B0','B1','B2','B3'],
                 'C':['C0','C1','C2','C3'],
                 'D':['D0','D1','D2','D3']},
                index=[0,1,2,3])

In [212]:
df1

A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

In [213]:
df2=pd.DataFrame({'A':['A4','A5','A6','A7'],
                 'B':['B4','B5','B6','B7'],
                 'C':['C4','C5','C6','C7'],
                 'D':['D4','D5','D6','D7']},
                index=[4,5,6,7])

In [214]:
df2

A   B   C   D
4  A4  B4  C4  D4
5  A5  B5  C5  D5
6  A6  B6  C6  D6
7  A7  B7  C7  D7

In [215]:
df3=pd.DataFrame({'A':['A8','A9','A10','A11'],
                 'B':['B8','B9','B10','B11'],
                 'C':['C8','C9','C10','C11'],
                 'D':['D8','D9','D10','D11']},
                index=[8,9,10,11])

In [216]:
df3

A    B    C    D
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [217]:
pd.concat([df1,df2,df3])

A    B    C    D
0    A0   B0   C0   D0
1    A1   B1   C1   D1
2    A2   B2   C2   D2
3    A3   B3   C3   D3
4    A4   B4   C4   D4
5    A5   B5   C5   D5
6    A6   B6   C6   D6
7    A7   B7   C7   D7
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

# TASK #12: PROJECT AND CONCLUDING REMARKS

- Define a dataframe named 'Bank_df_1' that contains the first and last names for 5 bank clients with IDs = 1, 2, 3, 4, 5 
- Assume that the bank got 5 new clients, define another dataframe named 'Bank_df_2' that contains a new clients with IDs = 6, 7, 8, 9, 10
- Let's assume we obtained additional information (Annual Salary) about all our bank customers (10 customers) 
- Concatenate both 'bank_df_1' and 'bank_df_2' dataframes
- Merge client names and their newly added salary information using the 'Bank Client ID'
- Let's assume that you became a new client to the bank
- Define a new DataFrame that contains your information such as client ID (choose 11), first name, last name, and annual salary.
- Add this new dataframe to the original dataframe 'bank_df_all'.

In [218]:
Bank_df_1=pd.DataFrame({'ID':[1,2,3,4,5],
                       'First_Name':['Madhavi','Gajanan','Kiran','Kirti','Purva'],
                       'Last_Name':['Girkar','Raut','Raut','Harne','Kanthikar']})
Bank_df_1

ID First_Name  Last_Name
0   1    Madhavi     Girkar
1   2    Gajanan       Raut
2   3      Kiran       Raut
3   4      Kirti      Harne
4   5      Purva  Kanthikar

In [219]:
Bank_df_2=pd.DataFrame({'ID':[6,7,8,9,10],
                       'First_Name':['Rita','Anjana','Rohan','Miley','Sagar'],
                       'Last_Name':['Rogers','Shaikh','Gawaskar','Cyrus','Robinsons']})
Bank_df_2

ID First_Name  Last_Name
0   6       Rita     Rogers
1   7     Anjana     Shaikh
2   8      Rohan   Gawaskar
3   9      Miley      Cyrus
4  10      Sagar  Robinsons

In [220]:
Salary_df=pd.DataFrame({'ID':[1,2,3,4,5,6,7,8,9,10],
                       'Annual_Salary[£]':[20000,30000,40000,15000,56000,43000,68000,82000,34000,12000]})

In [222]:
Bank_df_3=pd.concat([Bank_df_1,Bank_df_2])

In [223]:
Bank_df_3

ID First_Name  Last_Name
0   1    Madhavi     Girkar
1   2    Gajanan       Raut
2   3      Kiran       Raut
3   4      Kirti      Harne
4   5      Purva  Kanthikar
0   6       Rita     Rogers
1   7     Anjana     Shaikh
2   8      Rohan   Gawaskar
3   9      Miley      Cyrus
4  10      Sagar  Robinsons

In [225]:
Bank_df_4=pd.merge(Bank_df_3, Salary_df, on='ID')
Bank_df_4

ID First_Name  Last_Name  Annual_Salary[£]
0   1    Madhavi     Girkar             20000
1   2    Gajanan       Raut             30000
2   3      Kiran       Raut             40000
3   4      Kirti      Harne             15000
4   5      Purva  Kanthikar             56000
5   6       Rita     Rogers             43000
6   7     Anjana     Shaikh             68000
7   8      Rohan   Gawaskar             82000
8   9      Miley      Cyrus             34000
9  10      Sagar  Robinsons             12000

In [226]:
new_bank_df=pd.DataFrame({'ID':[11],
                       'First_Name':['Tony'],
                       'Last_Name':['Stark'],
                         'Annual_Salary[£]':[98000]})

In [227]:
new_bank_df

ID First_Name Last_Name  Annual_Salary[£]
0  11       Tony     Stark             98000

In [230]:
bank_df_all=pd.concat([Bank_df_4,new_bank_df])
bank_df_all

ID First_Name  Last_Name  Annual_Salary[£]
0   1    Madhavi     Girkar             20000
1   2    Gajanan       Raut             30000
2   3      Kiran       Raut             40000
3   4      Kirti      Harne             15000
4   5      Purva  Kanthikar             56000
5   6       Rita     Rogers             43000
6   7     Anjana     Shaikh             68000
7   8      Rohan   Gawaskar             82000
8   9      Miley      Cyrus             34000
9  10      Sagar  Robinsons             12000
0  11       Tony      Stark             98000

# EXCELLENT JOB!